name: Build OnePlus6 ReSukiSU Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          bc \
          bison \
          flex \
          build-essential \
          ccache \
          curl \
          git \
          zip \
          python3 \
          cpio \
          device-tree-compiler \
          libssl-dev \
          libelf-dev \
          gcc-aarch64-linux-gnu

    - name: Download clang
      run: |
        mkdir clang
        cd clang
        wget https://github.com/kdrag0n/proton-clang/releases/download/20210505/proton-clang.tar.gz
        tar xf proton-clang.tar.gz

    - name: Build kernel
      run: |
        chmod +x build.sh
        CLANG_DIR=$GITHUB_WORKSPACE/clang ./build.sh

    - name: Upload Image.gz-dtb
      uses: actions/upload-artifact@v4
      with:
        name: Image.gz-dtb
        path: kernel/out/arch/arm64/boot/Image.gz-dtb
